name = "AlgamesPlots"
uuid = "2c04b5eb-dcf4-427a-8cb2-62f746663c32"
authors = ["simon-lc <simonlc@stanford.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "0.12"
julia = "1"
